version: '3'

networks:
  backend_network: # Réseau privé API <-> DB (inaccessible de l'extérieur)
    internal: true

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
        - db_data:/var/lib/mysql
        - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
        interval: 5s
  api:
    build: ./node-api
    expose:
        - "3000" # API exposée uniquement à d'autres conteneurs du réseau
    ports:
      - "3000:3000"
    depends_on:
        db:
            condition: service_healthy
volumes:
    db_data: