version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
  bdd:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: bdd
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      bdd:
        condition: service_healthy

# Lancement des services
# docker-compose up -d